Repository arduino/compile-sketches, pull requests merged in 2023-03, with the labels that each got.

#105 Use `actions/setup-python` action to install Python for action
  .github/workflows/lint-python.yml
  .github/workflows/test-python.yml
  .python-version
  action-setup.sh
  action.yml
Labels: type: enhancement, topic: infrastructure

#106 Update project Python version to 3.11.2
  .python-version
Labels: type: enhancement, topic: infrastructure

#107 Use Poetry for Python dependencies management
  .github/workflows/lint-python.yml
  .github/workflows/lint-shell.yml
  .github/workflows/test-python.yml
  action-setup.sh
  action.yml
  compilesketches/.flake8
  compilesketches/requirements.txt
  compilesketches/tests/.coveragerc
  compilesketches/tests/pytest.ini
  compilesketches/tests/requirements.txt
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#108 Restore support for external Python package platform dependencies
  .github/workflows/test-integration.yml
  .github/workflows/testdata/platforms/PyserialDependent/boards.txt
  .github/workflows/testdata/platforms/PyserialDependent/platform.txt
  .github/workflows/testdata/platforms/PythonPackageDependent/boards.txt
  .github/workflows/testdata/platforms/PythonPackageDependent/dependent.py
  .github/workflows/testdata/platforms/PythonPackageDependent/platform.txt
  README.md
  action.yml
  docs/FAQ.md
  poetry.lock
  pyproject.toml
Labels: type: imperfection, topic: code

#109 Group action setup log output
  action.yml
Labels: type: imperfection, topic: code

#91 update set-output cmds
  .github/workflows/sync-labels.yml
  .github/workflows/test-integration.yml
Labels: type: imperfection, topic: infrastructure

#110 Sync infrastructure assets from upstream "templates"
  .codespellrc
  .flake8
  .github/dependabot.yml
  .github/workflows/check-action-metadata-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/lint-python.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/spell-check.yml
  .github/workflows/sync-labels-npm.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-python-poetry-task.yml
  .github/workflows/test-python.yml
  .github/workflows/validate-action_yml.yml
  .gitignore
  README.md
  Taskfile.yml
  compilesketches/.flake8
  compilesketches/compilesketches.py
  compilesketches/tests/pytest.ini
  compilesketches/tests/test_compilesketches.py
  etc/codespell-ignore-words-list.txt
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#113 Add infrastructure for checking project filesystem
  .github/workflows/check-files-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#114 Add infrastructure to check general file formatting
  .ecrc
  .editorconfig
  .github/workflows/check-general-formatting-task.yml
  .github/workflows/testdata/reports/all-inputs/arduino-avr-uno.json
  .github/workflows/testdata/reports/all-inputs/esp8266-esp8266-huzzah.json
  LICENSE.txt
  README.md
  Taskfile.yml
  compilesketches/tests/testdata/test_get_warning_count_from_output/has-warnings.txt
  compilesketches/tests/testdata/test_get_warning_count_from_output/no-warnings.txt
  docs/FAQ.md
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#115 Add CI workflow to check the license file
  .github/workflows/check-license.yml
  LICENSE.txt
  README.md
Labels: type: enhancement, topic: infrastructure

#116 Add CI workflow to check Markdown files for problems
  .github/workflows/check-markdown-task.yml
  .markdown-link-check.json
  .markdownlint.yml
  .markdownlintignore
  README.md
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#117 Add infrastructure to check for problems with npm configuration files
  .github/workflows/check-npm-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#118 Add infrastructure to check for Prettier formatting compliance
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/test-integration.yml
  .prettierignore
  README.md
  Taskfile.yml
  action.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#120 Add infrastructure for maintaining the table of contents
  .github/workflows/check-toc-task.yml
  README.md
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#121 Add infrastructure to validate GitHub Actions workflows
  .github/workflows/check-workflows-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#122 Add infrastructure to lint YAML files
  .github/workflows/check-yaml-task.yml
  .github/workflows/test-integration.yml
  .yamllint.yml
  README.md
  Taskfile.yml
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#123 Use correct syntax for empty YAML sequence
  .github/workflows/test-integration.yml
  README.md
  action.yml
  compilesketches/tests/test_compilesketches.py
Labels: type: imperfection, topic: documentation

#124 Add additional triggers to integration test workflow
  .github/workflows/check-action-metadata-task.yml
  .github/workflows/check-files-task.yml
  .github/workflows/check-general-formatting-task.yml
  .github/workflows/check-license.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-npm-task.yml
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/check-taskfiles.yml
  .github/workflows/check-toc-task.yml
  .github/workflows/check-yaml-task.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/test-integration.yml
  .github/workflows/test-python-poetry-task.yml
Labels: type: enhancement, topic: infrastructure

#128 Always add size summary report to sketches report
  compilesketches/compilesketches.py
  compilesketches/tests/test_compilesketches.py
Labels: type: enhancement, topic: code
